include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports # Absolute imports
    # - directives_ordering # Correct import order

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
